# IPvtl Cluster Manager 环境配置
# 复制此文件为 .env 并修改配置

# 调试模式
IPVTL_DEBUG=false

# 服务器配置文件路径
IPVTL_SERVERS_CONFIG_PATH=servers/servers.json

# 轮询配置
IPVTL_POLL_INTERVAL=30
IPVTL_POLL_TIMEOUT=10.0
IPVTL_POLL_MAX_CONCURRENT=10

# 通道操作超时
IPVTL_CHANNEL_STOP_TIMEOUT=30.0
IPVTL_CHANNEL_START_TIMEOUT=30.0
IPVTL_CHANNEL_RESTART_DELAY=2.0
